# gestor_front:
  #  resource: "@FrontEndBundle/Resources/config/routing.yml"
    #prefix:   /

#gestor_back:
    #resource: "@BackEndBundle/Resources/config/routing.yml"
    #prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
front:
    resource: "@FrontEndBundle/Controller/"
    type:     annotation
    prefix:   /

