gestor_front_homepage:
    path:     /
    defaults: { _controller: FrontEndBundle:Default:index }

gestor_front_principal:
    path:     /principal
    defaults: { _controller: FrontEndBundle:Default:principal }

gestor_front_login:
    path:     /login
    defaults: { _controller: FrontEndBundle:Default:login }

gestor_front_registrar:
    path:     /registrar
    defaults: { _controller: FrontEndBundle:Default:registrar }

gestor_front_empleado:
    path:     /empleado
    defaults: { _controller: FrontEndBundle:Default:empleado }
