services:
  gestor.front.principalService:
    class: FrontEndBundle\Services\principalService
    arguments: ["@doctrine.orm.entity_manager"]

  gestor.front.empleadoService:
    class: FrontEndBundle\Services\empleadoService
    arguments: ["@doctrine.orm.entity_manager"]

  gestor.front.loginService:
    class: FrontEndBundle\Services\loginService
    arguments: ["@doctrine.orm.entity_manager"]

  gestor.front.logoutService:
    class: FrontEndBundle\Services\logoutService
    arguments: ["@doctrine.orm.entity_manager"]

  gestor.front.registrarService:
    class: FrontEndBundle\Services\registrarService
    arguments: ["@doctrine.orm.entity_manager"]

  gestor.front.comprobarUsuarioService:
    class: FrontEndBundle\Services\comprobarUsuarioService
    arguments: ["@session", "@doctrine.orm.entity_manager"]

  gestor.front.clientesService:
    class: FrontEndBundle\Services\clientesService
    arguments: ["@doctrine.orm.entity_manager"]
  
  gestor.front.horarioService:
    class: FrontEndBundle\Services\horarioService
    arguments: ["@doctrine.orm.entity_manager"]

  gestor.front.luzService:
    class: FrontEndBundle\Services\luzService
    arguments: ["@doctrine.orm.entity_manager"]

  gestor.front.aguaService:
    class: FrontEndBundle\Services\aguaService
    arguments: ["@doctrine.orm.entity_manager"]

  gestor.front.proveedoresService:
    class: FrontEndBundle\Services\proveedoresService
    arguments: ["@doctrine.orm.entity_manager"]
  
  gestor.front.perfilService:
    class: FrontEndBundle\Services\perfilService
    arguments: ["@session", "@doctrine.orm.entity_manager"]


















